CREATE TABLE APP.TBL_RECIPES (
	REC_ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(64) UNIQUE,
	INSTRUCTIONS VARCHAR(255)
	);

DROP TABLE APP.TBL_RECIPES;

ALTER TABLE APP.TBL_RECIPES
	ADD COLUMN RECIPEINTRUCTIONS VARCHAR(255);
	
select * from APP.TBL_RECIPES;

CREATE TABLE APP.TBL_INGREDIENTS (
	INGREDIENTS_ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	
	TBL_RECIPES_ID INT,
	NAME VARCHAR(64) ,
	AMOUNT VARCHAR(64) ,
	MEASURE VARCHAR(64)
	);
	
DROP TABLE APP.TBL_INGREDIENTS;
	
select * from APP.TBL_INGREDIENTS;

